name: Jellyfin yt-dlp
run-name: Build container
on: [push]
env:
  - DOCKER_USERNAME = maxvdm
  - DOCKER_PASSWORD = MRw8BTsyhGCqy;cw
  - DOCKER_USERNAME_GITEA = max
  - DOCKER_PASSWORD_GITEA = H3[N^mDqFUV[9zCu
  - DOCKER_REGISTRY_GITEA - https://gitea.svdm.me

jobs:
  Build-container:
    runs-on: ubuntu-latest
    container:
      image: docker-latest:latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
      - name: Build container
        run: docker build --pull -t "gitea.svdm.me/max/jellyfin-ytdlp:latest" .
        
  deploy-container:
    runs-on: docker-latest
    steps:
      - name: Login to docker registry
        run: docker login -u "DOCKER_USERNAME_GITEA" -p "DOCKER_PASSWORD_GITEA" DOCKER_REGISTRY_GITEA
      - name: Push container to registry
        run: docker push gitea.svdm.me/max/jellyfin-ytdlp:latest