name: Jellyfin yt-dlp
run-name: Build container
on: [push]

jobs:
  Build-container:
    runs-on: docker-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@main
      - name: Build container
        run: docker build --pull -t "gitea.svdm.me/max/jellyfin-ytdlp:latest" .
        
  deploy-container:
    runs-on: docker-latest
    steps:
      - name: Login to docker registry
        run: docker login -u "DOCKER_USERNAME" -p "DOCKER_PASSWORD" DOCKER_REGISTRY
      - name: Push container to registry
        run: docker push gitea.svdm.me/max/jellyfin-ytdlp:latest