name: Jellyfin yt-dlp
run-name: Build container
on: [push]

jobs:

  buildx:
    runs-on: ubuntu-latest
    container:
      image: ubuntu-latest
    steps:
      - name: Login to the Container registry
        uses: docker/login-action@v2
        with:
          registry: hub.docker.com
          username: maxvdm
          password: $DOCKER_PASSWORD
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        platforms: amd64,arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        platforms: amd64,arm64
      - 
        name: Build container
        run: docker buildx build --platform amd64,arm64 --pull -t "gitea.svdm.me/max/jellyfin-ytdlp:latest" .
        
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      - name: Login to docker registry
        run: docker login -u "max" -p "H3[N^mDqFUV[9zCu" https://gitea.svdm.me
      - name: Push container to registry
        run: docker push gitea.svdm.me/max/jellyfin-ytdlp:latest