stages:

- build


services:

- docker:dind



docker_build:



stage: build



image: docker:latest
before_script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
script:
  - docker build -t gitea.svdm.me/max/jellyfin-ytdlp:latest .
  - docker push gitea.svdm.me/max/jellyfin-ytdlp:latest