name: Jellyfin yt-dlp
run-name: Build container
on: [push]

jobs:
  Build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build container
        run: docker build --pull -t "gitea.svdm.me/max/jellyfin-ytdlp:latest" .
        
  deploy-container:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
      - name: Login to docker registry
        run: docker login -u "max" -p "H3[N^mDqFUV[9zCu" https://gitea.svdm.me
      - name: Push container to registry
        run: docker push gitea.svdm.me/max/jellyfin-ytdlp:latest